language: ruby
cache: bundler
os: linux
before_install:
  - yes | gem update --system --force
  - gem install bundler
install:
  - bundle install
branches:
  only:
  - master
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
deploy:
  - provider: pages:git
    token: $GITHUB_TOKEN
    edge: true
    cleanup: false
    keep_history: true
    local_dir: ./site
    on:
      branch: master
