language: ruby
cache: bundler
os: linux
addons:
  apt:
    packages:
    - sshpass
before_install:
  - yes | gem update --system --force
  - gem install bundler
install:
  - bundle install
branches:
  only:
  - master
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
deploy:
  - provider: pages:git
    token: $GITHUB_TOKEN
    edge: true
    skip_cleanup: true
    keep_history: true
    local_dir: ./site
    on:
      branch: master
after_deploy:
  - sshpass -p $PASSWORD ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER "mkdir TEST"